name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: pwd
    - run: ls -al
    - run: docker compose version
    - name: Build and push services
      run: |
        docker compose build
        docker compose push
    - name: Copy compose file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        source: docker-compose.yml
        target: /opt/to/docker-compose/
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        script: |
          docker-compose -f /opt/docker-compose/docker-compose.yml pull
          docker-compose -f /opt/docker-compose/docker-compose.yml up -d
          docker system prune -af
#    - name: Deploy
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
#        port: 22
#        script: |
#          docker pull ${{ secrets.DOCKER_USERNAME }}/lame:latest
#          docker stop my_container
#          docker rm my_container
#          docker run --name my_container -d ${{ secrets.DOCKER_USERNAME }}/lame:latest
